= isActionVisible(name)
:navtitle: isActionVisible()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Documents the `isActionVisible(name)` function for the Calendar component in Dashboard component script. Returns a Boolean indicating whether the specified end-user feature (toolbar button or action) is visible/accessible. The `name` parameter is a String identifying the feature, such as 'Apply', 'Clear Calendar', 'Switch To Year View', etc. Can be called as `isActionVisible` (unqualified) or `Calendar1.isActionVisible` (qualified) in component script.
endif::ai[]

[WARNING,caption=See Also]
xref:thisViewsheetIsActionVisible.adoc[] to return Dashboard toolbar button visibility.


Returns the visibility/accessibility of the specified end-user feature.

== Parameters
name::			name of feature (String):
+
[source]
'Switch To Year View'
'Switch To Month View'
'Switch To Simple View'
'Switch To Date Range Mode'
'Clear Calendar'
'Apply'







== Example
[source,javascript]
if (Calendar1.isActionVisible('Apply')==true) {
  Text1.text = 'Press the Apply button to apply filter';
}




[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
isActionVisible              // unqualified
Calendar1.isActionVisible    // qualified

{secondForm}
====


