= dropdown
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
This page documents the `dropdown` property of the Calendar component in Dashboard scripting. It specifies a collapsible style for the calendar: set to `true` to collapse the calendar when not in use, or `false` (default) to keep it expanded. The property is a Boolean and can be used in component script as either `dropdown` (unqualified) or `Calendar1.dropdown` (qualified).
endif::ai[]

[WARNING,caption=See Also]
xref:dashboard:CalendarProperties.adoc[] for more information on user selection editing.



Specifies a collapsible style for the calendar.


== Type
Boolean::	`true`: collapse calendar when not in use +
`false`: do not collapse calendar (default)


== Example
[source,javascript]
Calendar1.dropdown = true;




[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
dropdown               // unqualified
Calendar1.dropdown    // qualified

{secondForm}
====


