= min
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: The `min` property specifies the earliest date available for selection on a Calendar component. It is of type Date and is used in Dashboard component script. Set it using a Date value, for example with CALC.today() or dateAdd(). See CalendarProperties for related user selection editing options.
endif::ai[]

[WARNING,caption=See Also]
xref:dashboard:CalendarProperties.adoc[] for more information on user selection editing.


Specifies the earliest date available to select on the Calendar.  Script that uses the `min` property should be placed on the Calendar *component*. See xref:AddScriptToDashboard.adoc#AddComponentScript[Add Component Script] for more information.


== Type
Date



== Example
[source,javascript]
Calendar1.max = CALC.today();
Calendar1.min = dateAdd('yyyy',-1,CALC.today()); // 1 year ago




[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
min               // unqualified
Calendar1.min     // qualified

====


