= daySelection
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: The `daySelection` property is a Boolean that specifies whether users can select individual days of the week on a Calendar component in Monthly view mode. When set to `true`, individual day selection is enabled; when `false` (the default), users must select the entire week. It applies to Calendar components in Dashboard script (component script or Dashboard script context).
endif::ai[]

[WARNING,caption=See Also]
xref:dashboard:CalendarProperties.adoc[] for more information on user selection editing.

Specifies that the user can select individual days of the week (when the Calendar is in ‘Monthly’ view mode). Otherwise, the user must select the week in its entirety.

== Type
Boolean::	`true`: enable individual day selection +
`false`: disable day selection (default)



== Example
[source,javascript]
Calendar1.daySelection = true;



[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
daySelection               // unqualified
Calendar1.daySelection    // qualified

{secondForm}
====


