= combinedTooltip
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: For a xref:dashboard:LineChart.adoc[], xref:dashboard:AreaChart.adoc[], or xref:dashboard:BarChart.adoc[] (including stacked bar), when set to `true`, displays a single tooltip with details from all series. The amount of data displayed will be limited by available space in the tooltip. When `false` (default), the tooltip displays details only for the series to which the user points.
endif::ai[]


For a xref:dashboard:LineChart.adoc[], xref:dashboard:AreaChart.adoc[], or xref:dashboard:BarChart.adoc[] (including stacked bar), when set to `true`, displays a single tooltip with details from all series. The amount of data displayed will be limited by available space in the tooltip. When `false` (default), the tooltip displays details only for the series to which the user points.

==  Type
Boolean:: `true`: Display combined tooltip +
`false`: Display individual tooltip


== Example
[source,javascript]
Chart1.combinedTooltip = true;



[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
combinedTooltip         // unqualified
Chart1.combinedTooltip  // qualified

{secondForm}
====


