= labelText
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies the text of the label displayed (Combo Box component *only*). See xref:dashboard:RadioCheckBoxComboProperties.adoc[] for information on the '`Label Text`' option.
endif::ai[]

[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:dashboard:RadioCheckBoxComboProperties.adoc[] for more information about Form components.
====


Specifies the text of the label displayed (Combo Box component *only*). See xref:dashboard:RadioCheckBoxComboProperties.adoc[] for information on the '`Label Text`' option.

== Type
String::	Label text


== Example
[source,javascript]
ComboBox1.labelVisible = true;
ComboBox1.labelText = 'Select a value';

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
labelText              // unqualified
ComboBox1.labelText    // qualified

{secondForm}
====
