= sortByValue
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies that the sorting specified by xref:CheckRadioComboSortType.adoc[] should be based on the values in the list rather than the labels. Default is `false` (i.e., sort by label, not by value).
endif::ai[]



[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for  properties shared with other components.
* xref:dashboard:RadioCheckBoxComboProperties.adoc[]for more information about Form components.
====


Specifies that the sorting specified by xref:CheckRadioComboSortType.adoc[] should be based on the values in the list rather than the labels. Default is `false` (i.e., sort by label, not by value).





== Type
Boolean:: `true`: sort items by value  +
`false`: sort items by label




== Example
[source,javascript]
ComboBox1.sortByValue = true;


[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
sortByValue            // unqualified
ComboBox1.sortByValue  // qualified

{secondForm}
====