= toolTip
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies a tooltip to be displayed on the Image component. Use placeholder `pass:[{0}]` to insert the data value from the Image, and format the inserted data using number formats. (See xref:dashboard:DataFormat.adoc#NumberFormat[Number Format] for more details on format strings.) You can additionally use HTML markup such as `<i>`, `<b>`, `<h1>`, `<u>`, `<small>`, `<br>` to format the tooltip contents.
endif::ai[]

[WARNING,caption=See Also]
====
xref:dashboard:ImageProperties.adoc[] for general information about Image components.
====

Specifies a tooltip to be displayed on the Image component. Use placeholder `pass:[{0}]` to insert the data value from the Image, and format the inserted data using number formats. (See xref:dashboard:DataFormat.adoc#NumberFormat[Number Format] for more details on format strings.) You can additionally use HTML markup such as `<i>`, `<b>`, `<h1>`, `<u>`, `<small>`, `<br>` to format the tooltip contents.





== Type
String::			The tooltip to display




== Example
[source,javascript]
Image1.toolTip = "<b>Total Sales</b>: {0,number,$##,###.00}";


[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
toolTip           // unqualified
Image1.toolTip    // qualified

{secondForm}
====


