= shadow
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Adds a drop shadow to the component. To set the shadow's color, opacity, direction, distance, and blur, see xref:OvalShadowInfo.adoc[] (the `shadowInfo` property).
endif::ai[]

[WARNING,caption=See Also]
====
[square]
* xref:OvalShadowInfo.adoc[] to set the shadow's color, opacity, direction, distance, and blur.
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:dashboard:ShapeProperties.adoc[] for more information about Oval components.
====

Adds a drop shadow to the component.  See xref:OvalShadowInfo.adoc[] to style the shadow.



== Type
Boolean:: `true`: add drop shadow +
`false`: no drop shadow



== Example
[source,javascript]
Oval1.shadow = true;

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
shadow           // unqualified
Oval1.shadow     // qualified

{secondForm}
====


