= contourCellSize
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies the size of the cells that make up the grid on which contour weights are computed for a xref:dashboard:ScatterContourChart.adoc[] or xref:dashboard:ContourMapChart.adoc[]. Higher values specify larger cells, and hence broader clusters. Lower values specify smaller cells, and hence smaller clusters.
endif::ai[]


Specifies the size of the cells that make up the grid on which contour weights are computed for a  xref:dashboard:ScatterContourChart.adoc[] or xref:dashboard:ContourMapChart.adoc[]. Higher values specify larger cells, and hence broader clusters. Lower values specify smaller cells, and hence smaller clusters.


== Type
Number


== Example


[source,javascript]
Chart1.contourCellSize = 4.7;




[TIP]
====
Either syntax below can be used in xref:dashboardscript:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
contourCellSize          // unqualified
Chart1.contourCellSize   // qualified

{secondForm}
====