= submitOnChange
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies that user selections should be submitted immediately to the server and the Dashboard refreshed with updated data (default). When this feature is disabled, user selections are not submitted until the user explicitly preforms a submit operation. (See xref:dashboard:DynamicallySetProperties.adoc[] and xref:dashboard:SubmitButtonProperties.adoc[] for more information.)
endif::ai[]

[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:dashboard:SliderSpinnerProperties.adoc[] for more information on Slider settings.
====





Specifies that user selections should be submitted immediately to the server and the Dashboard refreshed with updated data (default). When this feature is disabled, user selections are not submitted until the user explicitly preforms a submit operation. (See xref:dashboard:DynamicallySetProperties.adoc[] and xref:dashboard:SubmitButtonProperties.adoc[] for more information.)





== Type
Boolean::	`true`: submit user selections immediately (default) +
`false`: submit user selections on demand






== Example
[source,javascript]
Spinner1.submitOnChange = false;

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
submitOnChange              // unqualified
Spinner1.submitOnChange     // qualified

{secondForm}
====


