= labelPosition
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies the position of the label relative to the Spinner component. See xref:dashboard:SliderSpinnerProperties.adoc[] for information on the '`Label Position`' option.
endif::ai[]

[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:dashboard:SliderSpinnerProperties.adoc[] for more information on Spinner settings.
====

Specifies the position of the label relative to the Spinner component. See xref:dashboard:SliderSpinnerProperties.adoc[] for information on the '`Label Position`' option.

== Type
String::
* `'top'`: label appears above the component
* `'bottom'`: label appears below the component
* `'left'`: label appears to the left of the component (default)
* `'right'`: label appears to the right of the component


== Example
[source,javascript]
Spinner1.labelVisible = true;
Spinner1.labelPosition = 'top';

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
labelPosition             // unqualified
Spinner1.labelPosition    // qualified

{secondForm}
====
