// this is a comment
= InetSoft Documentation

InetSoft StyleBI  allows you to explore, analyze, monitor, report, and collaborate on business and operational data, all in real time.

The  topics in the left panel explain how to use the User Portal to create data sources, Data Worksheets, and Dashboards, as well as how to manage the server with Enterprise Manager.

[IMPORTANT]
StyleBI can be installed on any platform that supports Docker. For information on how to install Docker, see the https://docs.docker.com/engine/install/[Install Docker Engine] documentation.    For information on how to install StyleBI in a Docker container, see the StyleBI https://github.com/inetsoft-technology/stylebi/blob/main/README.md[README] file on GitHub.



'''


****
StyleBI is produced by InetSoft Technology, the leader in innovative and scalable Business Intelligence software. Please feel free to contact us with any questions!


Phone: +1.888.216.2353 (US) / +1.732.424.0400 (International)
Email: info@inetsoft.com / Web: https://www.inetsoft.com
****

