= Set Up the Example Data
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: How to set up the example data used by the examples and walkthroughs throughout this documentation (Sales Explore, All Sales, ProductSales, customers, Fast Go Game, Wireless Mouse, the Orders data source, Order Model, Census, Hurricane, Map Points, etc.). The examples come from the examples.zip file, which is imported in Enterprise Manager. Some example Data Worksheets contain their own (embedded) data and work as soon as they are imported. Others query the example ‘Orders’ database, a PostgreSQL database that the StyleBI Quickstart docker-compose.yaml starts automatically (the ‘postgres’ service, loaded from orders.sql). If you installed StyleBI without the Quickstart files, you must add this database yourself or those examples show no data. Readers without administrator access should ask their administrator to set up the example data, or install their own copy of StyleBI with the Quickstart procedure.
endif::ai[]

The examples in this documentation use a common set of sample Dashboards, Data Worksheets, and data sources. Set them up once, as described below, to follow the examples in the documentation.

The example assets are in the https://github.com/inetsoft-technology/stylebi/blob/v1.1.0/community-examples/examples.zip[*examples.zip*] file. Some of them contain their own data, and will work as soon as you import the file. Others use the example *Orders* database, which must also be running.

To set up the example data, follow the instructions for your installation:
[square]
* xref:#Quickstart[]: You installed StyleBI using  the Quickstart procedure from the https://github.com/inetsoft-technology/stylebi[StyleBI README on GitHub].
* xref:#OtherInstall[]: You installed StyleBI some other way.

Setting up the example data requires administrator access to the server. If you do not have this access, ask your administrator to set up the example data, or install your own copy of StyleBI using the Quickstart procedure, which includes everything that the examples need.

[#ExampleRequirements]
.Documentation Example Requirements
[cols="2,2,1",options="header"]
|===
|Example asset |Location |Requires the Orders database?

|‘Call Center Monitoring’, ‘Census Data’, ‘Construction Data’, ‘Hurricane’, ‘Map Points’, ‘Order Details’, and ‘Sales Revenue’ Data Worksheets
|menu:Data Worksheet[Examples]
|No

|‘Census’, ‘Call Center Monitoring’, ‘Construction Dashboard’, ‘Hurricane’, ‘Return Analysis’, and ‘Sales Summary’ Dashboards
|menu:Dashboard[Examples]
|No

|‘Sales Explore’, ‘ProductSales’, ‘Analysis’, and ‘Projection’ Data Worksheets
|menu:Data Worksheet[Examples]
|Yes

|‘All Sales’, ‘customers’, ‘Fast Go Game’, ‘Wireless Mouse’, and ‘sales by state’ Data Worksheets
|menu:Data Worksheet[Sample Queries]
|Yes

|‘Projection’ Dashboard
|menu:Dashboard[Examples]
|Yes

|‘Orders’ data source, including the ‘Order View’ physical view and the ‘Order Model’ and ‘Return Model’ data models
|menu:Data Source[Examples]
|Yes
|===



[#Quickstart]
== Quickstart Installation

If you installed StyleBI by following the Quickstart instructions in the StyleBI https://github.com/inetsoft-technology/stylebi/blob/main/README.md[README] file (using the *community-examples.zip* file from the https://github.com/inetsoft-technology/stylebi/releases[StyleBI Releases] page), the Orders database is already running. The Quickstart *docker-compose.yaml* file starts  the `postgres` service and loads  the *orders.sql* file automatically.

You only need to import the example assets:

. Locate the *examples.zip* file in the folder where you extracted *community-examples.zip*.
+
TIP: Use this copy of *examples.zip*, rather than one downloaded separately, so that the examples match your version of StyleBI.

. Import *examples.zip* in Enterprise Manager. See xref:administration:ImportExportAssets.adoc#ImportAssets[Import Assets] for instructions. (This requires access to Enterprise Manager.)

. To confirm that the example database is connected, open the ‘Sales Explore’ Data Worksheet in the menu:Data Worksheet[Examples] folder. Click the ‘Sales’ data block to select it. In the bottom panel, press the {buttonChangeView} and choose {buttonLiveDataView}. The data block should display rows of data.

[#OtherInstall]
== Other Installations

If you installed StyleBI *without* the Quickstart files, the Orders database will  not be running, and the examples that require it (see xref:#ExampleRequirements[xrefstyle=short]) will not display any data. To add the database, follow the steps below.

. Download the *community-examples.zip* file for your version of StyleBI from the https://github.com/inetsoft-technology/stylebi/releases[StyleBI Releases] page, and extract it. It contains the *orders.sql* and *examples.zip* files.

. Create the Orders database, using one of the following methods:
+
--
[square]
* *Add a PostgreSQL service to your Docker Compose file.* Copy *orders.sql* into the folder that contains your *docker-compose.yaml* file, and add the following service to the file. The service must be named `postgres`, because the example ‘Orders’ data source connects to a server with this host name.
+
[source,yaml]
----
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: inetsoft
      POSTGRES_PASSWORD: inetsoft
      POSTGRES_DB: orders
    volumes:
      - "./orders.sql:/docker-entrypoint-initdb.d/orders.sql:ro"
----
+
Then restart your containers with `docker compose up -d`.

* *Use an existing PostgreSQL server.* Create a database named `orders` on the server, and run the *orders.sql* script in that database.
--

. Import *examples.zip* in Enterprise Manager. See xref:administration:ImportExportAssets.adoc#ImportAssets[Import Assets] for instructions.

. If you used an existing PostgreSQL server, or if the examples do not display data, edit the ‘Orders’ data source (in the menu:Data Source[Examples] folder) as described in xref:user:EditConnection.adoc[]:
+
[square]
* Set the connection URL to point to your database server, for example `jdbc:postgresql://__hostname__:5432/orders`.
* Enter the user name and password for the database. (For the Docker Compose service shown above, the user name and password are both `inetsoft`.)

. To confirm that the example database is connected, open the ‘Sales Explore’ Data Worksheet in the menu:Data Worksheet[Examples] folder. Click the ‘Sales’ data block to select it. In the bottom panel, press the {buttonChangeView} and choose {buttonLiveDataView}. The data block should display rows of data.
