= CALC.amordegrc(cost, date_purchased, first_period, salvage, period, rate, [basis])
:navtitle: CALC.amordegrc()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


Returns the depreciation of an asset for accounting year `period` on a prorated basis according to the *degressive* method of the French accounting system. {CALCExcelFunctionPage} This function is similar to xref:CALC_amorlinc.adoc[] except that the depreciation coefficient is calculated based on the life of the asset:

[width=50%]
|===
|Life of asset|Depreciation coefficient

| 0-2 years | 1
| 3-4 years | 1.5
| 5-6 years | 2
| >6 years | 2.5
|===

Depreciation during the first (fractional) period is given by:
[source,javascript]
cost * rate/100 * CALC.yearfrac(date_purchased,first_period,basis)

Depreciation during (whole) periods 1 and 2 is given by:
[source,javascript]
rate * cost

Depreciation during the final (fractional) period is the difference between the asset’s value in the previous period and the asset’s salvage value. The function returns 0 for periods after which the asset has already reached its salvage value.

== Parameters
cost::				Initial cost of the asset
date_purchased::				Date object: Asset purchase date
first_period::				Date object: End of the first period
salvage::				Salvage value at end of asset life
period::				Period (year) for which to return depreciation
rate::				Rate of depreciation
basis::            {basis}:
+
include::partial$basisTable.adoc[]










== Example
Depreciation over time of a $2400 asset purchased on August 19, 2008, with first depreciation period ending December 31, 2008, end-of-life salvage value of $300, 15% rate of depreciation, and Actual/360 counting method.
[source,javascript]
----
var deprec = 0;
for(var period = 0; period < 7; period++) {
  deprec = CALC.amordegrc(2400, new Date(2008,7,19), new Date(2008,11,31), 300, period, 0.15, 2);
  alert('Period ' + period + ': Depreciation of ' + deprec);
}

// Returns:
// Period 0: Depreciation of 335
// Period 1: Depreciation of 774
// Period 2: Depreciation of 484
// Period 3: Depreciation of 303
// Period 4: Depreciation of 189
// Period 5: Depreciation of 158
// Period 6: Depreciation of 0
----

include::partial$expressionColOrCalcField.adoc[]
[source,javascript]
CALC.amordegrc(2400, field['PurchaseDate'], field['DeprecDate'], 300, period, 0.15, 2);

include::partial$dashboardScriptData.adoc[]
[source,javascript]
----
CALC.amordegrc(2400, RangeSlider1.selectedObjects[0], RangeSlider1.selectedObjects[1], 300, period, 0.15, 2);
CALC.amordegrc(2400, parameter.PurchaseDate, parameter.DeprecDate, 300, period, 0.15, 2);
----





include::partial$readMoreCalcFieldTypes.adoc[]