= CALC.fv(rate, nper, pmt, [pv], [type])
:navtitle: CALC.fv()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


Returns the *future value* of an investment based on periodic, constant payments and a constant interest rate. {CALCExcelFunctionPage}

== Parameters
rate::			Interest rate per period
nper::			Total number of payment periods in an annuity
pmt::			constant payment made each period (default=0)
pv::			Present value (default=0)
+
NOTE: Typically, `pmt` contains principal and interest but no other fees or taxes. If `pmt` is omitted (`null`), you must include the `pv` argument, the lump-sum amount that a series of future payments is worth right now (for a loan, this is the original loan amount). If `pv` is omitted (`null`), it is assumed to be 0 (typical for a bond), and you must include the `pmt` argument.

type::			Timing of payment +
`0`: payment at end of period (default) +
`1`: payment at start of period





== Example
Future value of a $5000 loan with 6% annual interest rate, 10 payment periods, and $300 payment at start of each period. (Note that payments are entered as negative values.)

[source,javascript]
----
CALC.fv(0.06/12, 10, -300, 5000, 1); // returns -2171.9506981443483
----
The result indicates that payment of approximately $2171.95 will be required at the end of the term. If no payments are made (`pmt=0`), then the final payment will be $5255.70, as shown below.
[source,javascript]

CALC.fv(0.06/12, 10, 0, 5000, 1); // returns -5255.700660203947

include::partial$expressionColOrCalcField.adoc[]
[source,javascript]
CALC.fv(field['Rate'], 10, 0, 5000, 1)

include::partial$dashboardScriptData.adoc[]
[source,javascript]
----
CALC.fv(Slider1.selectedObject, 10, 0, 5000, 1)
CALC.fv(parameter.Rate, 10, 0, 5000, 1)
----





include::partial$readMoreCalcFieldTypes.adoc[]