= CALC.ipmt(rate, per, nper, pv, fv, type)
:navtitle: CALC.ipmt()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


Returns the *interest* in a given period’s payment for an investment based on periodic constant *payments* and a constant interest rate. {CALCExcelFunctionPage}

TIP: Use  xref:CALC_ppmt.adoc[] to calculate the portion of capital in a given payment. Use xref:CALC_pmt.adoc[] to calculate the total payment (capital and interest).



== Parameters
rate::			Interest rate per period
per::			Period for which to return interest (between 1 and `nper`)
nper::			Total number of payment periods in an annuity
pv::			Present value (positive for a loan, negative for an investment),  the lump-sum amount that a series of future payments is worth right now
fv::			Future value (generally 0 for a loan),  the cash balance you want to attain after the last payment is made
type::			Timing of payment +
`0`: payment at end of period (default) +
`1`: payment at start of period







== Example
Amount of interest in each of the first ten payments for an $8000 two-year loan with 10% annual interest and payment at end of period. (The negative values indicates that these are payments.)

[source,javascript]
----
for(var period = 1; period <=10; period++){
  alert('Period ' + period +': ' + CALC.ipmt(0.1/12, period, 12*2, 8000, 0, 0))
}

// Returns:
// Period 1: -66.66666666666667
// Period 2: -64.14589379972111
// Period 3: -61.60411449221768
// Period 4: -59.04115369048507
// Period 5: -56.45683488207135
// Period 6: -53.85098008358753
// Period 7: -51.223409828449675
// Period 8: -48.57394315451896
// Period 9: -45.902397591638874
// Period 10: -43.20858914906812
----


include::partial$expressionColOrCalcField.adoc[]
[source,javascript]
CALC.ipmt(field['Rate'], period, 12*2, 8000, 0, 0)

include::partial$dashboardScriptData.adoc[]
[source,javascript]
----
CALC.ipmt(Slider1.selectedObject, period, 12*2, 8000, 0, 0)
CALC.ipmt(parameter.Rate, period, 12*2, 8000, 0, 0)
----





include::partial$readMoreCalcFieldTypes.adoc[]