= CALC.pmt(rate, nper, pv, fv, type)
:navtitle: CALC.pmt()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


Returns the periodic *payment* for a loan based on constant payments and a constant interest rate. {CALCExcelFunctionPage}

TIP: Use xref:CALC_ppmt.adoc[] to calculate the portion of capital in a given payment. Use  xref:CALC_ipmt.adoc[] to calculate the portion of interest in a given payment.


== Parameters
rate::			Interest rate per period
nper::			Total number of monthly payments for the loan
pv::			Present value (positive for a loan, negative for an investment), the lump-sum amount that a series of future payments is worth right now
fv::			Future value (generally 0 for a loan), a cash balance you want to attain after the last payment is made
type::			Timing of payment: +
`0`: payment at end of period (default) +
`1`: payment at start of period



== Example
Payment at start of each period for a $10,000 2-year loan with 8% interest per period. (Negative values indicate payments.)


[source,javascript]
----
CALC.pmt(0.08/12, 24, 10000, 0, 1);
// returns -449.27772969719734 (approx $449.28 per period)
----


include::partial$expressionColOrCalcField.adoc[]
[source,javascript]
CALC.pmt(field['Rate'], 24, 10000, 0, 1)

include::partial$dashboardScriptData.adoc[]
[source,javascript]
----
CALC.pmt(Slider1.selectedObject, 24, 10000, 0, 1)
CALC.pmt(parameter.Rate, 24, 10000, 0, 1)
----





include::partial$readMoreCalcFieldTypes.adoc[]