= formatDate(date,string)
:navtitle: formatDate()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Formats a date according to a simple date format and returns the result as a string.


== Parameters
date::				Java or JavaScript date object
string::	`'LONG'`, `'FULL'`, `'MEDIUM'`,  `'SHORT'`, or a date pattern string, using the symbols below:

+
include::partial$dateFormatTable.adoc[]



== Examples
.Sample usage
[source,javascript]
--
var dateToday = formatDate(new Date(), "hh 'o''clock' a, zzzz");
--

Some format string pattern examples are shown below:

|===
|Date and time pattern|Result

|`yyyy.MM.dd G ‘at’ HH:mm:ss z`|2006.08.07 AD at 02:19:35 PDT
|`EEE, MMM d, ‘ ‘ yy`|Mon, Aug 7, ‘06
|`h:mm a`|12:08 PM
|`hh ‘o’ ‘clock’ a, zzzz`|12 o’clock PM, Pacific Daylight Time
|===

The predefined options (`'LONG'`,`'FULL'`,`'MEDIUM'`,`'SHORT'`) are *locale-adapting* formats, which means they will display in a manner determined by the user's locale, for example, "`Wednesday, May 22, 2025`" in an English locale and "`2025年5月22日`" in a Chinese locale.

|===
|Predefined string |Result

|`FULL`| Thursday, June 5, 2025
| `LONG`| June 5, 2025
|`MEDIUM`| Jun 5, 2025
|`SHORT`| 6/5/25
|===



include::partial$expressionColOrCalcField.adoc[]
[source,javascript]
formatDate(field['Date'], "hh 'o''clock' a, zzzz");

include::partial$dashboardScriptData.adoc[]
[source,javascript]
formatDate(parameter.Date, "hh 'o''clock' a, zzzz");


include::partial$readMoreCalcFieldTypes.adoc[]