= Script Statements
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

The  following topics  introduce some  important JavaScript language constructs.

== Assigment Operators
An assignment operator assigns a value to its left operand based on the value of its right operand.

[source,javascript]
x = y;

Arithmetic operators and bitwise operators can be combined with the assignment operator as a short hand for performing a computation and assigning the results to a variable.

[source,javascript]
x += y;

== Comparison Operators
A comparison operator compares two values and returns `true` or `false` depending on the comparison result.

[cols="1,3"]
|===
|Operator|Description

|==|Equal
|!=|Not equal
|>|Greater than
|>=|Greater than or equal to
|<|Less than
|<=|Less than or equal to
|===

Note that these operators *cannot* be used to compare Date objects. Use date functions instead, such as `dateDiff()` or `CALC.dateValue()`. See xref:DateObjectFunctions.adoc[] for more information about date functions.

== Variable Definition
A variable statement inside a function declares a local variable. A variable statement outside of a function body declares a global variable.

.Example: Define a variable  without assignment
[source,javascript]
var val;

.Example: Define a variable  with assignment
[source,javascript]
var array1 = [1, 2, 3];

== Function Definition
The `function` keyword introduces a new function in the global scope. Once a function is defined, it can be called in other parts of the script.

.Example: Function to sum values in a numerical array
[source,javascript]
----
// Define function 'sumarray'
function sumarray(arr) {
  var total = 0;
  for(var idx = 0; idx < arr.length; idx++) {
    total += arr[idx];
  }
  return total;
}

// Call function 'sumarray'
var myArray = [2,3,4,5,6];
var myTotal = sumarray(myArray);
----

== if
The `if` conditional structure executes the statements within the ‘if’ block only when the specified condition is `true`. Alternative conditions can be tested by using one or more optional ‘else if’ blocks. An optional final ‘else’ block will be executed if all other conditions evaluate `false`.

[source,javascript]
if(condition0) {
  // statements to execute if condition0 is true
}
else if(condition1) {
  // statements to execute if condition1 is true
}
else if(condition2) {
  // statements to execute if condition2 is true
}
else if(condition3) {
  // statements to execute if condition3 is true
}
else {
  // statements to execute if all above conditions are false
}

[#TryCatch]
== try-catch
The “try-catch” construction allows you to catch a script error before it causes Dashboard execution to fail. To catch an error, place the desired sequence of code inside a `try` block. If any line of this `try` code generates an error, program execution immediately jumps to the code in the `catch` block.

[source,javascript]
try {
  // Code to try
}
catch(err) {
  // Alternative code for case of error
  log(err.stack);
}
finally {
  // Code to execute in either case
}

The `err` parameter contains the exception message that was generated by the `try` block. Use the `stack` property to log explicit information about script errors, as shown above. The `finally` block contains code to be executed whether an error occurred or not. The `catch` block and `finally` block are optional, but cannot both be omitted.

== for
A ‘for’ loop consists of three optional expressions, enclosed in parentheses and separated by semi-colons.

[source,javascript]
for([init-expression];[condition];[increment-expression]) {
  //statements;
}

The init-expression is evaluated before the loop starts. It is normally used to declare and initialize a counter variable. The condition statement is evaluated at the beginning of every loop. If the condition is `true`, the statements are executed. Otherwise, the loop terminates. The increment-expression is executed after the body statements. It is normally used to increment the counter variable.

.Typical '`for`' loop
[source,javascript]
for(var idx = 0; idx < array1.length; idx++) {
 //...
}

A special ‘for’ loop allows iteration through all properties of an object. If the object is an array, each item in the array is treated as a property.

.Object iteration
[source,javascript]
var props = "";
for(var item in obj) {
  props += item + " = " + obj[item];
}



== While
A ‘while’ statement is a loop with a single condition. The condition is evaluated at the beginning of every loop. If the condition is true, the body of the loop is executed. Otherwise, the loop is terminated.

[source,javascript]
while(condition) {
  statements;
}


A variation of the ‘while’ statement is ‘do...while’. Instead of evaluating the condition at the beginning of the loop, ‘do...while’ statement evaluates the condition at the end of a loop. This guarantees the loop is at least executed once.

[source,javascript]
do {
  // statements
}
while(condition);

A loop can be terminated in the body by inserting a ‘break’ statement. A ‘break’ statement causes the execution to immediately transfer to the point following the end of the loop. Similarly, a ‘continue’ statement interrupts the execution of a loop and transfer the execution to the end of the loop block.

== switch
A ‘switch’ statement evaluates an expression and matches its result with a list of choices. If a match is found, the statements under the choice are executed. Otherwise, if a ‘default’ label exists, the statements in the default block are executed.

[source,javascript]
switch(expression) {
case label1:
  //statements;
  break;
case label2:
  //statements;
  break;
//...
default:
  //statements;
}

== with
A ‘with’ statement establishes an object as the default object for a set of statements.

[source,javascript]
with(object) {
  // statements;
}

The properties and methods of the object can be referenced without qualifying the names with the object name:

[source,javascript]
with(Text1) {
  text = "contents of this text element";
}