= AxisSpec.setMinPadding(Number)
:navtitle: setMinPadding()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Specifies the padding space in pixels for the minimum (lowest value) axis label. The corresponding getter function is `getMinPadding()`.

== Parameter
Number:: Padding in pixels for the minimum axis label

== Example

.Chart Component Script
[source,javascript]
--
var spec = new AxisSpec();
spec.setMinPadding(10); // <1>
--
<1> Set 10 pixels of padding at the minimum label end of the axis.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]

[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetYScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on. For example:

[source,javascript]
--
var coord = Chart1.getCoordinate();
var scale = coord.getYScale();
var spec = scale.getAxisSpec();
spec.setMinPadding(10);
--
=====
