= AxisSpec.setAxisSize(Number)
:navtitle: setAxisSize()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Specifies a fixed size for the axis area in pixels. For a vertical axis, this sets the width; for a horizontal axis, this sets the height. The corresponding getter function is `getAxisSize()`.

== Parameter
Number:: Fixed size of the axis area in pixels

== Example

.Chart Component Script
[source,javascript]
--
var spec = new AxisSpec();
spec.setAxisSize(80); // <1>
--
<1> Set the axis area to a fixed width/height of 80 pixels.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]

[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetYScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on. For example:

[source,javascript]
--
var coord = Chart1.getCoordinate();
var scale = coord.getYScale();
var spec = scale.getAxisSpec();
spec.setAxisSize(80);
--
=====
