= AxisSpec.setFontFrame(frame)
:navtitle: setFontFrame()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Specifies a mapping between axis label values and fonts. The corresponding "getter" function is `getFontFrame()`.

== Parameter
frame:: A `FontFrame` object

== Example

.Chart Component Script
[source,javascript]
--
dataset = [["State", "Quantity"], ["NJ", 200], ["NY", 300]]; //<1>
graph = new EGraph();
var elem = new IntervalElement("State", "Quantity");
var sscale = new CategoricalScale("State");
var aspec = new AxisSpec(); //<2>
var frame = new StaticFontFrame(); //<3>
frame.setFont(java.awt.Font("Dialog", java.awt.Font.BOLD, 14));
aspec.setFontFrame(frame); //<4>
sscale.setAxisSpec(aspec);
graph.setScale("State", sscale);
graph.addElement(elem);
--
<1> {dataset}
<2> Create the `AxisSpec` object.
<3> Create the `FontFrame` object.
<4> Use `setFontFrame` to assign the `FontFrame` to the axis.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]


[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetXScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on. For example:

[source,javascript]
--
var coord = graph.getCoordinate(); //<1>
var scale = coord.getXScale(); //<2>
var spec = scale.getAxisSpec(); //<3>

var frame = new StaticFontFrame();
frame.setFont(java.awt.Font("Dialog", java.awt.Font.BOLD, 14));
spec.setFontFrame(frame);
--
=====
