= AxisSpec.setGridBetween(Boolean)
:navtitle: setGridBetween()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Specifies whether grid lines are drawn between tick marks rather than at tick marks. {noGetter}

== Parameter
Boolean:: `true`: draw grid lines between ticks +
`false`: draw grid lines at ticks

== Example

.Chart Component Script
[source,javascript]
--
var spec = new AxisSpec();
spec.setGridBetween(true); // <1>
--
<1> Draw grid lines between tick marks.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]

[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetYScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on. For example:

[source,javascript]
--
var coord = Chart1.getCoordinate();
var scale = coord.getYScale();
var spec = scale.getAxisSpec();
spec.setGridBetween(true);
--
=====
