= AxisSpec.setAllTicks(Boolean)
:navtitle: setAllTicks()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Specifies whether tick marks are displayed for labels that have been suppressed by the `setAbbreviate()` option. When abbreviation is enabled, some labels are dropped to conserve space; this property controls whether tick marks remain visible at those positions. {noGetter}

== Parameter
Boolean:: `true`: show ticks for abbreviated (suppressed) labels +
`false`: hide ticks for abbreviated (suppressed) labels

== Example

.Chart Component Script
[source,javascript]
--
var spec = new AxisSpec();
spec.setAbbreviate(true);
spec.setAllTicks(true); // <1>
--
<1> Show ticks even for labels dropped by abbreviation.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]

[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetXScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on. For example:

[source,javascript]
--
var coord = Chart1.getCoordinate();
var scale = coord.getXScale();
var spec = scale.getAxisSpec();
spec.setAllTicks(true);
--
=====
