= AxisSpec.setFacetGrid(Boolean)
:navtitle: setFacetGrid()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

Specifies whether grid lines extend across axis labels, as in a facet table layout. {noGetter}

== Parameter
Boolean:: `true`: grid lines extend across labels +
`false`: grid lines do not extend across labels

== Example

.Chart Component Script
[source,javascript]
--
var spec = new AxisSpec();
spec.setFacetGrid(true); // <1>
--
<1> Enable facet-style grid lines across axis labels.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]

[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetXScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on. For example:

[source,javascript]
--
var coord = Chart1.getCoordinate();
var scale = coord.getXScale();
var spec = scale.getAxisSpec();
spec.setFacetGrid(true);
--
=====
