= AxisSpec.setFontFrame(frame)
:navtitle: setFontFrame()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

ifdef::ai[]
Summary: Reference for the AxisSpec.setFontFrame() method in Chart API scripts. Specifies a mapping between axis label values and fonts using a CategoricalFontFrame object, allowing individual axis labels to be displayed in different fonts. The corresponding getter is getFontFrame().
endif::ai[]

Specifies a mapping between axis label values and fonts. The corresponding "getter" function is `getFontFrame()`.

== Parameter
frame:: A `CategoricalFontFrame` object (`inetsoft.graph.aesthetic.CategoricalFontFrame`)

== Example

.Chart Component Script
[source,javascript]
----
include::scriptexample:partial$AxisSpecSetFontFrame1.js[]
----
<1> {dataset}
<2> Create the `AxisSpec` object.
<3> Create the `CategoricalFontFrame` object and map values to fonts.
<4> Use `setFontFrame` to assign the `FontFrame` to the axis.

include::chartAPI:partial$scriptThatModifiesGraph.adoc[]


[TIP]
=====
To change the property on a Chart that was *previously created* with the Chart Editor, use xref:chartAPI:EGraphGetCoordinate.adoc[] ①, xref:chartAPI:RectCoordGetXScale.adoc[] ②, and xref:chartAPI:ScaleGetAxisSpec.adoc[] ③ to obtain a handle to the desired xref:chartAPI:Coordinate.adoc[] object, xref:chartAPI:Scale.adoc[] object, and so on.
=====
