= GShape
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Chart Script API reference for `GShape`. This is part of StyleBI's Chart Script (Chart API) scripting layer — a last-resort approach for chart customization/interactivity. See chartAPI:ChartScriptTutorial.adoc for guidance on when to use scripting vs. UI-driven alternatives (built-in toolbar tools, Ad Hoc Editor, Form-driven dynamic properties).
endif::ai[]

[WARNING,caption=See Also]
====
[square]
* xref:ShapeForm.adoc[] for information on using `GShapes` as decorative shapes.
* xref:StaticShapeFrame.adoc[] for information on using `GShapes` as static shapes.
====


The `GShape` object contains a set of shapes. For element properties requiring a `GShape` object, the shape can be specified as a xref:GShapeImageShape.adoc[] (user-defined image) or as one of the following constants:

include::partial$gShapeConstants.adoc[]

`GShape` provides the following methods:
[square]
include::ROOT:partial$MINITOC_Gshape.adoc[]