= Customize Portal Login
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
How to customize the StyleBI User Portal login page by modifying and replacing the login.html and login.css files in the inetsoft web resources directory inside a custom Docker image. The login.html file goes in /usr/local/inetsoft/classes/inetsoft/web/resources/ and the login.css file goes in a css subfolder at that same location. When altering CSS styles, the id attributes of all input and button elements in login.html must be preserved. Other assets such as images can be referenced via the Storage settings. Customizations apply only to the Portal, not to Enterprise Manager. Customizing the login JavaScript requires contacting technical support. InetSoft does not support these customizations and does not guarantee compatibility with future versions.
endif::ai[]

To customize the Portal login page, follow the steps below:

CAUTION: Customizations that you make to the login page are not supported by InetSoft and are not guaranteed to be compatible with future versions.

. Modify the  xref:ROOT:attachment$login.html[login.html] page to suit your needs.

. Place the customized *login.html* file in the following directory.

+
__pass:[/usr/local/inetsoft/classes/inetsoft/web/resources/] __

+
include::partial$derivedDockerImage.adoc[]
+
TIP: Make sure you maintain the *id* attributes of all `<input>` and `<button>` elements in the *login.html* file if you plan to alter the CSS styles.  {SampleYAML}

. Modify the  xref:ROOT:attachment$login.css[login.css] file  to suit your needs.

. Place the customized *login.css* file in a _css_ folder  relative to the location of the *login.html* file. For example:
+
__pass:[ /usr/local/inetsoft/classes/inetsoft/web/resources/css] __
+
include::partial$derivedDockerImage.adoc[]

. To reference other assets such as images in  the _login.html_ and _login.css_ files, see xref:administration:Storage.adoc[] in xref:administration:ManageServer.adoc[].

NOTE: Customizations that you make in the *login.html* and *login.css* files apply only to the Portal and not to Enterprise Manager. If you want to customize the JavaScript that performs login and validation, please contact {technicalSupport} for assistance.
