= Automate Administrative Tasks
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

include::ROOT:partial$enterpriseOnly.adoc[]

InetSoft provides a Groovy DSL that wraps the https://www.inetsoft.com/docs/2023/apidoc/[public client API]. This makes it easy to automate administration and deployment tasks. The DSL is a wrapper for the interfaces in the https://www.inetsoft.com/docs/2023/apidoc/index.html?inetsoft/client/package-summary.html[inetsoft.client] package and the data structures in the https://www.inetsoft.com/docs/2023/apidoc/index.html?inetsoft/web/api/package-summary.html[inetsoft.web.api] package used by those interfaces.

TIP: The Groovy DSL is *not required* to use the client API. The Java API may be used directly from any JVM language. For remote repositories, you can use any language with the public web APIs. The web APIs are RESTful with JSON as the data transfer mechanism. The advantage of using the DSL is that you do not need to configure the classpath when running the client script or application, and the scripts are less verbose.

See xref:GroovyDSLScriptingFramework.adoc[] for instructions on how to create scripts that access API methods. See the following sections for built-in administration functions that you can run from the command line.