= Connect to a Repository
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

include::ROOT:partial$enterpriseOnly.adoc[]


You must use the *Administration Console* to  connect to a repository before running certain commands, and you can only be connected to one repository at a time.

== Open the Administration Console

To run the  *Administration Console*, use the following command:


 docker run -it --rm 636869400126.dkr.ecr.us-east-2.amazonaws.com/inetsoft/stylebi-enterprise:1.0 shell


To connect to a *non-running* server (not recommended) add the  `-v` flag as shown below:

 docker run -it --rm -v enterprise_inetsoft_blob:/var/lib/inetsoft/blob -v enterprise_inetsoft_kv:/var/lib/inetsoft/kv 636869400126.dkr.ecr.us-east-2.amazonaws.com/inetsoft/stylebi-enterprise:1.0 shell

To download or upload files from a *running server* (where '_/local/directory/path_' is the directory where the file is to be uploaded from or downloaded to), add the  `-v` flag as shown below:

 docker run -it --rm -v /local/directory/path:/arbitrary/container/path 636869400126.dkr.ecr.us-east-2.amazonaws.com/inetsoft/stylebi-enterprise:1.0 shell



== Connect to a Repository
The `:connect` command makes the connection to a repository.

=== Parameter
path:: 			File-system path to a local repository or URL of a remote repository.
user:: The user name used to authenticate with the repository. If security is not enabled, this should be “admin”.
organization:: In a multi-tenant environment, the user's organization ID.  (See xref:EnableMultiTenant.adoc[].)  If omitted, the Host Organization is assumed.
password:: The password used to authenticate with the repository.

.connect
[example]
====
 :connect http://www.example.com admin admin
====

== Disconnect from a Repository

The `:disconnect` command disconnects the current repository connection (if one exists).

.disconnect
[example]
====
 :disconnect
====
