= Connect to a Repository
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

include::ROOT:partial$enterpriseOnly.adoc[]


You must use the *Administration Console* to  connect to a repository before running certain commands, and you can only be connected to one repository at a time.

== Open the Administration Console

To run the  *Administration Console*, use the following command:


 docker run -it --rm ghcr.io/inetsoft-technology/stylebi-enterprise:latest shell


To connect to a *non-running* server (not recommended) add the  `-v` flag as shown below:

 docker run -it --rm -v inetsoft_blob:/var/lib/inetsoft/blob -v inetsoft_kv:/var/lib/inetsoft/kv ghcr.io/inetsoft-technology/stylebi-enterprise:latest shell

TIP: Volume names `inetsoft_blob` and `inetsoft_kv` may vary based on the host environment.


To download or upload files from a *running server* (where '_/local/directory/path_' is the directory where the file is to be uploaded from or downloaded to), add the  `-v` flag as shown below:

 docker run -it --rm -v /local/directory/path:/arbitrary/container/path ghcr.io/inetsoft-technology/stylebi-enterprise:latest shell



== Connect to a Repository
The `:connect` command makes the connection to a repository.

=== Parameter
path:: 			File-system path to a local repository or URL of a remote repository.
user:: The user name used to authenticate with the repository. If security is not enabled, this should be “admin”.
organization:: In a multi-tenant environment, the user's organization ID.  (See xref:EnableMultiTenant.adoc[].)  If omitted, the Host Organization is assumed.
password:: The password used to authenticate with the repository.

.connect
[example]
====
 :connect http://www.example.com admin admin
====

== Disconnect from a Repository

The `:disconnect` command disconnects the current repository connection (if one exists).

.disconnect
[example]
====
 :disconnect
====
