= Localize a Dashboard
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


You can use a simple text mapping to localize most text in a  Dashboard. The first step in setting up localization for a particular  Dashboard is to assign *Text IDs* to each text element to be mapped. You can do this in the  ‘Options’ dialog box of Visual Composer.  See xref:viewsheet:LocalizeDashboard.adoc[] in xref:viewsheet:VisualizeYourData.adoc[] for more information on how to assign Text IDs.


== Create SreeBundle Mapping File
After you have assigned Text IDs to  Dashboard elements, you can create the mapping file  that specifies the text substitutions for these elements.  (This is *the same file* that you use for mapping data source names.  See xref:LocalizeDataSource.adoc[].)

IMPORTANT: The localization cannot take effect until you register the locale in Enterprise Manager.  See xref:RegisterLocale.adoc[].


=== File Name
The mapping file should be ASCII text and should have the  name

 SreeBundle_{language}_{country}.properties

where `pass:[{language}]` and  `pass:[{country}]` are https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html[Java-supported two-letter codes] for locale language and country. For example, the localization mapping file for Canadian French speakers should be called _SreeBundle_fr_CA.properties_. This  file must be placed in the _/usr/local/inetsoft/classes/inetsoft/util_ directory.

[NOTE]
====
[square]
* The country code is *optional*. You can omit the country code from the filename (i.e., use only the language code in the filename) to create a single mapping file that will be loaded for any country matching the specified language.
* If a mapping file matching  the user’s locale selection *cannot be found* at runtime, no localization is performed.
* For non-Latin alphabets, convert a native UTF-8 text file to ASCII by using the native2ascii program bundled with the JDK, and specify the encoding. For example:
+
 native2ascii -encoding UTF-8 Hebrew.txt > SreeBundle_iw_IL.properties
====

=== File Contents
Each Dashboard translation is specified by a single line of text in the  localization file:

 {element_id}={translated_element}

The `pass:[{element_id}]` is the *Text ID* assigned to the  Dashboard element in  Visual Composer. Spaces and certain other non-alphanumeric characters in the `pass:[{element_id}]` must be escaped by a backslash, for example, ‘Head\ 1’. The `pass:[{translated_element}]` is the translated text that you want to appear in the corresponding  Dashboard element. Spaces in the `pass:[{translated_element}]` do not need to be escaped.

.French translation
[example]
====
The French Canadian localization file mentioned above, _SreeBundle_fr_CA.properties_, might contain the following lines of text, where, for purposes of illustration, `State_fr` is used as the French translation of `State`, and so on:

 title=Localized Title_fr
 state\ header=State_fr
 sales\ header=Sales_fr

The above mapping translates the text corresponding to three Text IDs, (which might be assigned in a  Dashboard) into the specified mock French text:

|===
|Text ID|Translated Text

|title|Localized Title_fr
|state header|State_fr
|sales header|Sales_fr
|===
====

== Find Available Localization Targets
include::administration:partial$DownloadBundle.adoc[]


