= setActionVisible(name, Boolean)
:navtitle: setActionVisible()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

[WARNING,caption=See Also]
xref:thisViewsheet.adoc#thisViewsheetSetActionVisible[thisViewsheet.setActionVisible()] to show or hide Dashboard toolbar buttons.


Sets the visibility/accessibility of end-user Chart features. To disable a feature, set the value to `false`.





== Parameters
name::			name of chart function (String):
+
.Dragging
[source]
'AxisResize' (drag to resize axis)
'LegendResize' (drag to resize legend)
'LegendMove' (drag to move legend)
+
.Buttons
[source]
'Brush'
'Clear Brushing'
'Edit'
'Maximize'
'Show Data'
'Show Details'
'Zoom'
'Exclude Data'
'Clear Zoom'
'Enable Manual Refresh'
'Enable Auto Refresh'
'Refresh'
'Drill Down Filter'
'Hide MiniToolbar'
'Menu Actions' ('More' button)
'Sort Axis' (button next to axis)

+
.Right-click menu options
[source]
'Resize Plot'
'Properties'
'Format'
'Save Image As'
'Annotate Component'
'Annotate Point'
'Axis Properties'
'Hide Axis'
'Title Properties'
'Hide Title'
'Group'
'Filter'
'Ungroup'
'Rename'
'Legend Properties'
'Hide Legend'
'Show All Titles'
'Show All Axes'
'Show Legend'

Boolean:: `false`: hide the specified function +
`true`: show the specified function

== Example
[source,javascript]
Chart1.setActionVisible("Show Details", false);





[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
setActionVisible               // unqualified
Chart1.setActionVisible    // qualified

{secondForm}
====


