= Chart


[WARNING,caption=See Also]
====
[square]
* xref:chartAPI:ChartScriptTutorial.adoc[] for examples of complex chart scripting.
* xref:CommonProperties.adoc[] for  properties shared with other components.
====


The following topics present basic properties available to Chart components. See xref:chartAPI:ChartScriptReference.adoc[] for details about more advanced properties.

[square]
**** xref:viewsheetscript:General.adoc[]
**** xref:viewsheetscript:ChartAxisProperties.adoc[]
**** xref:viewsheetscript:MeasureAxisProperties.adoc[]
**** xref:viewsheetscript:AxisTitleProperties.adoc[]
**** xref:viewsheetscript:PlotProperties.adoc[]
**** xref:viewsheetscript:ChartBindingInfo.adoc[]

[IMPORTANT]
====
Charts are unique among all  components in that you can access many Chart properties via both simple script properties and low-level Chart API methods.

[square]
* For information on using simple scriptable Chart properties, see the above sections.  This approach produces scripts that are easier to read and maintain.
* For information on low-level Chart API methods, see xref:chartAPI:ChartScriptReference.adoc[]. The API provides full control over all aspects of Chart data and presentation, but may yield more complex and verbose scripts.

Note that scripted Charts are not good candidates for user-modification, so you should *deselect* ‘Enable Ad Hoc Editing’ in the Chart Properties dialog box.
====
