= maxDate
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]



[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for  properties shared with other components.
* xref:viewsheet:RadioCheckBoxComboProperties.adoc[]for more information about Form components.
====

Specifies the latest selectable date when the ComboBox is configured to use a *calendar interface* for Date or TimeInstant type data. (See xref:viewsheet:RadioCheckBoxComboProperties.adoc[] for information on setting the ‘Calendar’ option.)  This property should be set in the *onInit* handler  (See xref:AddScriptToDashboard.adoc#AddDashboardScript[Add Dashboard Script] for more information about handlers.)


== Type
Date::		Latest selectable date on ComboBox calendar









== Example
[source,javascript]
ComboBox1.minDate = dateAdd('yyyy',-1,CALC.today());
ComboBox1.maxDate = dateAdd('yyyy',1,CALC.today());


[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
maxDate            // unqualified
ComboBox1.maxDate  // qualified

{secondForm}
====