= labelPosition
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:viewsheet:RadioCheckBoxComboProperties.adoc[] for more information about Form components.
====

Specifies the position of the label relative to the component (Combo Box component *only*). See xref:viewsheet:RadioCheckBoxComboProperties.adoc[] for information on the '`Label Position`' option.

== Type
String::
* `'top'`: label appears above the component
* `'bottom'`: label appears below the component
* `'left'`: label appears to the left of the component (default)
* `'right'`: label appears to the right of the component


== Example
[source,javascript]
ComboBox1.labelVisible = true;
ComboBox1.labelPosition = 'TOP';

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
labelPosition              // unqualified
ComboBox1.labelPosition    // qualified

{secondForm}
====
