= selectedObject
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


[WARNING,caption=See Also]
====
[square]
* xref:CheckRadioComboValues.adoc[] to access the values assigned to the component.
* xref:CommonSelectedLabel.adoc[] to access the label corresponding to the value.
* xref:CommonSelectedObjects.adoc[] to access the currently selected values  in multivalued components.
* xref:AccessComponentData.adoc[] for more information about `selectedObject`.
* xref:viewsheet:WriteBackToStorage.adoc#AccessMostRecentUserModification[Access the Most Recent User Modification] to retrieve the most recent modified object.
====



Specifies the selected *value* of the component (not the label). Applies to single-value input elements (Slider, Spinner, Radio Button, Combo Box) and the tabs of co-located components (Tabbed Interface).

TIP: To avoid *overwriting* an existing setting (saved by the designer, or saved by the user in a bookmark),  test to see if the component value has already been set before using `selectedObject`.  See xref:CommonSelectedObjects.adoc[] for an example of such a test.



== Type
Value of the selected option

Examples::
[source,javascript]
----
// Set a RadioButton with data type  ‘String’:
RadioButton1.selectedObject = 'NJ';

// Set a ComboBox with data type  ‘Date’:
ComboBox1.selectedObject = new Date(2020,5,23);


----




[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
selectedObject               // unqualified
Component1.selectedObject    // qualified

{secondForm}
====




