= setActionVisible(name, Boolean)
:navtitle: setActionVisible()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

[WARNING,caption=See Also]
xref:thisViewsheetSetActionVisible.adoc[] to show or hide Dashboard toolbar buttons.




Sets the visibility/accessibility of end-user Crosstab features. To disable a feature, set the value to `false`.

NOTE: The 'Sort Column' setting overrides the `sort.crosstab.aggregate` and `sort.crosstab.dimension` property settings in Enterprise Manager.

== Parameters
name::			Name of Crosstab function (String):
+
[source]
--
'Menu Actions' <1>
'Export' <2>
'Show Details' <3>
'Sort Column' <4>
--
<1> The {buttonMore}.
<2> The {buttonExport}. Applies also when the Crosstab is used as a xref:viewsheet:AddTipsToChart.adoc#DataTip[Data Tip].
<3> For xref:viewsheet:AddFreehandTable.adoc[Freehand Table.]
<4> The column header {buttonSort}.

Boolean:: `false`: hide the specified function +
`true`: show the specified function

== Example
[source,javascript]
Crosstab1.setActionVisible("Show Details", false);






[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
setActionVisible               // unqualified
Crosstab1.setActionVisible    // qualified

{secondForm}
====


