= setActionVisible(name, Boolean)
:navtitle: setActionVisible()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

[WARNING,caption=See Also]
xref:thisViewsheet.adoc#thisViewsheetSetActionVisible[thisViewsheet.isActionVisible()] to return Dashboard toolbar button visibility.




Sets the visibility/accessibility of end-user Crosstab features. To disable a feature, set the value to `false`.

NOTE: The 'Sort Column' setting overrides the `sort.crosstab.aggregate` and `sort.crosstab.dimension` property settings in Enterprise Manager.

== Parameters
name::			name of Crosstab function (String):
+
[source]
'Menu Actions' ('More' button)
'Export'
'Show Details' (Freehand Table)
'Sort Column'  (column header 'Sort' button)

Boolean:: `false`: hide the specified function +
`true`: show the specified function

== Example
[source,javascript]
Crosstab1.setActionVisible("Show Details", false);






[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
setActionVisible               // unqualified
Crosstab1.setActionVisible    // qualified

{secondForm}
====


