= length
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:viewsheet:RangeSliderProperties.adoc[] for more information on user selection editing.
====

Specifies the initial slider range. For a numerical field, this gives the range as a multiple of the minimum length xref:RangeSliderRangeSize.adoc[]. For example, if `length` is 3 and `rangeSize` is 100, the initial slider range is 300. For a date field, the units are specified by the xref:RangeSliderRangeType.adoc[] setting (year, month, or day). In either case, the user can subsequently readjust the range as desired.

== Type
Number::			Slider size, as multiple of minimum length






== Example
[source,javascript]
RangeSlider1.length = 3;


[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
length                  // unqualified
RangeSlider1.length     // qualified

{secondForm}
====


