= showCurrentSelection
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

// metadata for AI
ifdef::ai[]
Summary: Specifies whether the Selection Container displays the current state of all Dashboard selection components.
endif::ai[]


[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:viewsheet:SelectionContainerProperties.adoc[] for more information on user selection editing.
====

Specifies whether the Selection Container displays the current state of all Dashboard selection components.





== Type
Boolean:: `true`: display all current selections +
`false`: do not display current selections



== Example
[source,javascript]
CurrentSelection1.showCurrentSelection = false;

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
showCurrentSelection                       // unqualified
CurrentSelection1.showCurrentSelection     // qualified

{secondForm}
====


