= event

[WARNING,caption=See Also]
xref:WriteBackToDatabase.adoc#AccessUserModifiedData[Access User-Modified Data], for additional discussion of the `event` object.



The event object can be used within a Dashboard *onRefresh* handler  (see xref:AddScriptToDashboard.adoc#AddDashboardScript[Add Dashboard Script]) to provide information about the user’s most recent action in  Form Components, editable Tables, and Filter Components (Selection List, Selection Tree, Range Slider, Calendar).

NOTE: User interactions with Input components, editable tables, and Selection components automatically re-execute the Dashboard *onRefresh* handler.


The `event` object is instantiated at runtime when a user makes an interaction of the appropriate type, so you should *test for  existence* before attempting to access its properties:


.Example: Test for existence of event
[source,javascript]
if(event!=null) {
  // access 'event' properties, such as...
  // event.name, event.type, event.source, etc.
}

== Event Properties for Editable Table
For an Editable Table, the `event` object provides the following properties:

event.name:: The name of the table component.
event.type:: The type of the component, always `'table'`.
event.row:: The index of the row in the table which the user modified.
event.column:: The index of the column in the table which the user modified.
event.source:: A reference to the table object which can be used to access table properties.

== Event Properties for Form/Selection
For a Form component or Selection component, the event object provides the following properties:

event.name:: The name of the component, e.g., `'SelectionList1'`
event.type:: The type of the component: `'radiobutton'`, 'checkbox', 'combobox', 'textinput', 'selectionlist', 'selectiontree', 'rangeslider', `calendar`
event.source:: A reference to the component which can be used to access component properties, for example: `event.source.title='New Title'`.