= data
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


include::partial$readOnly.adoc[]

[WARNING,caption=See Also]
====
xref:viewsheetscript:AccessComponentData.adoc#TableCrosstabComponents[Table/Crosstab Components]  in xref:AccessComponentData.adoc[] for information about working with table data.
====



Two-dimensional array containing the original table or crosstab data (prior to grouping and aggregation). If no grouping or summarization is defined for the table, the `data` property is the same as the  xref:TableTable.adoc[] property. Otherwise, `data` holds the raw data and `table` holds the summarized data. The data can be referenced using the row number as the first array index and the column number or label as the second array index.

== Type
Two-dimensional array







== Examples
.Alert based on Table data
[source,javascript]
for (var i=1; i < data.length; i++) {
  if (Query1.data[i]['Name'] == 'Web Bridge') {
    alert('Note: "Web Bridge" will be discontinued.');
  }
}


.Compute a KPI from Table data
[source,javascript]
Text1.text = 'Grand total is ' + sum(Query1.data['Total']);






[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
data                 // unqualified
TableView1.data      // qualified

{secondForm}
====


