= table
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


include::partial$readOnly.adoc[]

[WARNING,caption=See Also]
====
xref:viewsheetscript:AccessComponentData.adoc#TableCrosstabComponents[Table/Crosstab Components]  in xref:viewsheetscript:AccessComponentData.adoc[]  for information about working with table data.
====




Two-dimensional array holding the table or crosstab cell data as displayed (after any grouping and aggregation). If no grouping or summarization is defined on a table, the `table` property is the same as the  xref:TableData.adoc[]  property. Otherwise, `data` holds the raw data and `table` holds the summarized data. The data can be referenced using the row number as the first array index and the column number or name as the second array index.

This property is read-only. To write data to an *Editable Table*, use  xref:viewsheetscript:TableSetObject.adoc[] or xref:TableSetCellValue.adoc[].


== Type
Two-dimensional array


== Examples
.Alert based on Table data
[source,javascript]
for (var i=1; i<table.length; i++) {
  if (Query1.table[i]['Name'] == 'Web Bridge'){
    alert('Note: "Web Bridge" will be discontinued.');
  }
}


.Compute a KPI from Table data
[source,javascript]
Text1.text = 'Grand total is ' + sum(Query1.table['Total']);






[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
table                 // unqualified
TableView1.table      // qualified

{secondForm}
====


