= applyChanges()
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]


For an *Embedded Table* in a Dashboard, writes the user-modified data into the corresponding Embedded Table in the Data Worksheet. See xref:viewsheet:TableProperties.adoc[] for information on making a Table editable.




== Example
The script below can be placed in the *onClick* handler of a Submit button. See xref:AddScriptToDashboard.adoc#AddComponentScript[Add Component Script] for more information about the onClick handler.


[source,javascript]
----
Table1.applyChanges();
saveWorksheet();

// Refresh the Dashboard with saved data from the Data Worksheet:
refreshAfterSubmit = true;

----

See xref:SpecialFunctionsSaveWorksheet.adoc[] and xref:CommonRefreshAfterSubmit.adoc[] for more information about these functions.




[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
applyChanges                 // unqualified
TableView1.applyChanges      // qualified

{secondForm}
====


