= col
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

include::partial$readOnly.adoc[]



[WARNING,caption=See Also]
====
* xref:viewsheetscript:TableTable.adoc[] for more information about the `table` array.
* xref:viewsheet:TableProperties.adoc[] for general information about the Table component.
====




Returns the column index of the cell currently referenced by a *Format* expression script. For example, if you specify a ‘Color’ expression in the *Format* panel for a *detail cell* in a Table, you can use the `col` property within the script to obtain the index of the column. This, together with xref:viewsheetscript:TableTable.adoc[] array and the xref:viewsheetscript:TableRow.adoc[] property allow you to construct relative references to other cells in the Table.

See xref:viewsheet:DynamicallySetProperties.adoc#ControlPropertieswithExpression[Control Properties with Expression] for information about how to use expressions to set properties.

== Example
The script below can be used in a ‘Color’ or ‘Background’ expression to set color formatting on a Table detail cell. It assigns a red color if the value in the cell is less than the value of the same cell in the row above, and assigns a green color otherwise.

[source,javascript]
----
 if (row > 1) {
  if (value < table[row-1][col]) {
    [255,0,0]
  }
  else {
    [0,255,0]
  }
}
----



