= labelPosition
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

[WARNING,caption=See Also]
====
[square]
* xref:CommonProperties.adoc[] for properties shared with other components.
* xref:viewsheet:TextInputProperties.adoc[] for more information on TextInput settings.
====

Specifies the position of the label relative to the TextInput component. See xref:viewsheet:TextInputProperties.adoc[] for information on the '`Label Position`' option.

== Type
String::
* `'top'`: label appears above the component
* `'bottom'`: label appears below the component
* `'left'`: label appears to the left of the component (default)
* `'right'`: label appears to the right of the component


== Example
[source,javascript]
TextInput1.labelVisible = true;
TextInput1.labelPosition = 'top';

[TIP]
====
Either syntax below can be used in  xref:AddScriptToDashboard.adoc#AddComponentScript[component script]:
[source,javascript]
labelPosition               // unqualified
TextInput1.labelPosition    // qualified

{secondForm}
====
