= Configure Self-Service

The following sections explain how you can configure self-service features to enable users to most effectively create their own  dashboards.




== Security

To allow users to take advantage of dashboard features, you must configure certain security settings to provide the appropriate level of access. (See xref:administration:ConfigureSecurity.adoc[] for general information about security features.)

Read/Write Permission:: Provide read and write access to *repository locations* where you want the user to save dashboards, and assign read permission for *data sources*, queries, and data models that the user might need. See xref:administration:SetRepositoryPermissions.adoc[] for instructions on how to do this.

Action Permission:: Provide access to the relevant self-service *actions*, such as ‘Portal Tabs’, ‘Visual Composer (Dashboard)’, and ‘My Dashboards’. See xref:administration:SetSecurityActions.adoc[] for instructions on how to do this.

== Dashboard Settings

There are some settings that you may want to adjust to facilitate end-user self-service for individual dashboards.

Ad Hoc Editing:: For Chart and Crosstab components in a Dashboard, turn on ‘Enable Ad Hoc Editing’. This will allow end users to modify these components without opening the Dashboard in Visual Composer. See xref:viewsheet:ChartProperties.adoc[] and xref:viewsheet:CrosstabProperties.adoc[] for more information.

Ad Hoc Filtering:: To enable a user to add filters into a Dashboard without opening the Dashboard in Visual Composer, add a Selection Container into the dashboard, and enable the ‘Allow User to Add/Remove Selections’ property. See xref:viewsheet:SelectionContainerProperties.adoc[] for more details.
