= Physical View
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

The basis of a data model is the *physical view*, which specifies a set of database tables and the joins that relate them. The physical view does not represent a *particular* query that retrieves specific fields, but rather outlines the full join structure that will enable arbitrary queries to be generated on an *ad hoc* basis. When a dashboard accesses a set of attributes from a data model, the joins that you have pre-specified in the physical view  permit the necessary query to be constructed automatically.

A physical view is not directly accessed by dashboard designers or end users. Designers and users have access only to the *logical models* defined from the physical model. (See xref:LogicalModel.adoc[].) Your goal in creating a physical model is to specify the appropriate relationships between the database tables containing the data required by users.

TIP: If you make a change to the structure of the database schema, press the ‘Refresh Metadata’ button on the toolbar to update the physical model.

Physical models are independent of one another; that is, relationships in one physical model do not impact relationships defined in a different physical model. You can create multiple physical models from a given data source, and it is common practice to model a single schema with multiple overlapping physical models. However, a given data model relies on just a single physical model.