= Use the Portal
%experimental%
include::ROOT:partial$buttonSnippets.adoc[]

The User Portal provides features for accessing and managing existing assets, such as Data Worksheets and Dashboards, and allows you to create new assets as well. The User Portal is a web-based interface, so you do not need to install any special software on your computer. Your system administrator will tell you the correct address to use in your web browser.


The following sections explain how to perform common tasks in the User Portal:

[square]
** xref:user:OpenUserPortal.adoc[]: Access the User Portal in your browser.
** xref:user:ConfigurePortal.adoc[]: Explains how to  change your password and email.
** xref:user:ManageRepository.adoc[]:
** xref:user:UseDashboard.adoc[]
** xref:viewsheet:UseFilterComponents.adoc[]
** xref:viewsheet:UseCharts.adoc[]
** xref:user:BookmarkDashboard.adoc[]
** xref:viewsheet:AddAnnotation.adoc[]
** xref:user:ProfileDashboard.adoc[]
** xref:user:ScheduleDashboard.adoc[]
** xref:user:DeployDashboard.adoc[]
** xref:viewsheet:ShareDashboard.adoc[]

